// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: order.proto

package orderpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Zip           string                 `protobuf:"bytes,3,opt,name=zip,proto3" json:"zip,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Delivery) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Delivery) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Delivery) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Delivery) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Delivery) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Delivery) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   string                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentDt     int64                  `protobuf:"varint,6,opt,name=payment_dt,json=paymentDt,proto3" json:"payment_dt,omitempty"`
	Bank          string                 `protobuf:"bytes,7,opt,name=bank,proto3" json:"bank,omitempty"`
	DeliveryCost  int32                  `protobuf:"varint,8,opt,name=delivery_cost,json=deliveryCost,proto3" json:"delivery_cost,omitempty"`
	GoodsTotal    int32                  `protobuf:"varint,9,opt,name=goods_total,json=goodsTotal,proto3" json:"goods_total,omitempty"`
	CustomFee     int32                  `protobuf:"varint,10,opt,name=custom_fee,json=customFee,proto3" json:"custom_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *Payment) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *Payment) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Payment) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetPaymentDt() int64 {
	if x != nil {
		return x.PaymentDt
	}
	return 0
}

func (x *Payment) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *Payment) GetDeliveryCost() int32 {
	if x != nil {
		return x.DeliveryCost
	}
	return 0
}

func (x *Payment) GetGoodsTotal() int32 {
	if x != nil {
		return x.GoodsTotal
	}
	return 0
}

func (x *Payment) GetCustomFee() int32 {
	if x != nil {
		return x.CustomFee
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChrtId        int64                  `protobuf:"varint,1,opt,name=chrt_id,json=chrtId,proto3" json:"chrt_id,omitempty"`
	TrackNumber   string                 `protobuf:"bytes,2,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Rid           string                 `protobuf:"bytes,4,opt,name=rid,proto3" json:"rid,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Sale          int32                  `protobuf:"varint,6,opt,name=sale,proto3" json:"sale,omitempty"`
	Size          string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	TotalPrice    int32                  `protobuf:"varint,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	NmId          int64                  `protobuf:"varint,9,opt,name=nm_id,json=nmId,proto3" json:"nm_id,omitempty"`
	Brand         string                 `protobuf:"bytes,10,opt,name=brand,proto3" json:"brand,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetChrtId() int64 {
	if x != nil {
		return x.ChrtId
	}
	return 0
}

func (x *Item) GetTrackNumber() string {
	if x != nil {
		return x.TrackNumber
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *Item) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Item) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Item) GetNmId() int64 {
	if x != nil {
		return x.NmId
	}
	return 0
}

func (x *Item) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Item) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderUid          string                 `protobuf:"bytes,1,opt,name=order_uid,json=orderUid,proto3" json:"order_uid,omitempty"`
	TrackNumber       string                 `protobuf:"bytes,2,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	Entry             string                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	Delivery          *Delivery              `protobuf:"bytes,4,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Payment           *Payment               `protobuf:"bytes,5,opt,name=payment,proto3" json:"payment,omitempty"`
	Items             []*Item                `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Locale            string                 `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`
	InternalSignature string                 `protobuf:"bytes,8,opt,name=internal_signature,json=internalSignature,proto3" json:"internal_signature,omitempty"`
	CustomerId        string                 `protobuf:"bytes,9,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DeliveryService   string                 `protobuf:"bytes,10,opt,name=delivery_service,json=deliveryService,proto3" json:"delivery_service,omitempty"`
	Shardkey          string                 `protobuf:"bytes,11,opt,name=shardkey,proto3" json:"shardkey,omitempty"`
	SmId              int32                  `protobuf:"varint,12,opt,name=sm_id,json=smId,proto3" json:"sm_id,omitempty"`
	DateCreated       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	OofShard          string                 `protobuf:"bytes,14,opt,name=oof_shard,json=oofShard,proto3" json:"oof_shard,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetOrderUid() string {
	if x != nil {
		return x.OrderUid
	}
	return ""
}

func (x *Order) GetTrackNumber() string {
	if x != nil {
		return x.TrackNumber
	}
	return ""
}

func (x *Order) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *Order) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *Order) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Order) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Order) GetInternalSignature() string {
	if x != nil {
		return x.InternalSignature
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetDeliveryService() string {
	if x != nil {
		return x.DeliveryService
	}
	return ""
}

func (x *Order) GetShardkey() string {
	if x != nil {
		return x.Shardkey
	}
	return ""
}

func (x *Order) GetSmId() int32 {
	if x != nil {
		return x.SmId
	}
	return 0
}

func (x *Order) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreated
	}
	return nil
}

func (x *Order) GetOofShard() string {
	if x != nil {
		return x.OofShard
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUid      string                 `protobuf:"bytes,1,opt,name=order_uid,json=orderUid,proto3" json:"order_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderUid() string {
	if x != nil {
		return x.OrderUid
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\bDelivery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x10\n" +
	"\x03zip\x18\x03 \x01(\tR\x03zip\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"\xb2\x02\n" +
	"\aPayment\x12 \n" +
	"\vtransaction\x18\x01 \x01(\tR\vtransaction\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"payment_dt\x18\x06 \x01(\x03R\tpaymentDt\x12\x12\n" +
	"\x04bank\x18\a \x01(\tR\x04bank\x12#\n" +
	"\rdelivery_cost\x18\b \x01(\x05R\fdeliveryCost\x12\x1f\n" +
	"\vgoods_total\x18\t \x01(\x05R\n" +
	"goodsTotal\x12\x1d\n" +
	"\n" +
	"custom_fee\x18\n" +
	" \x01(\x05R\tcustomFee\"\x8a\x02\n" +
	"\x04Item\x12\x17\n" +
	"\achrt_id\x18\x01 \x01(\x03R\x06chrtId\x12!\n" +
	"\ftrack_number\x18\x02 \x01(\tR\vtrackNumber\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\tR\x03rid\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04sale\x18\x06 \x01(\x05R\x04sale\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x05R\n" +
	"totalPrice\x12\x13\n" +
	"\x05nm_id\x18\t \x01(\x03R\x04nmId\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\tR\x05brand\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"\x80\x04\n" +
	"\x05Order\x12\x1b\n" +
	"\torder_uid\x18\x01 \x01(\tR\borderUid\x12!\n" +
	"\ftrack_number\x18\x02 \x01(\tR\vtrackNumber\x12\x14\n" +
	"\x05entry\x18\x03 \x01(\tR\x05entry\x12.\n" +
	"\bdelivery\x18\x04 \x01(\v2\x12.order.v1.DeliveryR\bdelivery\x12+\n" +
	"\apayment\x18\x05 \x01(\v2\x11.order.v1.PaymentR\apayment\x12$\n" +
	"\x05items\x18\x06 \x03(\v2\x0e.order.v1.ItemR\x05items\x12\x16\n" +
	"\x06locale\x18\a \x01(\tR\x06locale\x12-\n" +
	"\x12internal_signature\x18\b \x01(\tR\x11internalSignature\x12\x1f\n" +
	"\vcustomer_id\x18\t \x01(\tR\n" +
	"customerId\x12)\n" +
	"\x10delivery_service\x18\n" +
	" \x01(\tR\x0fdeliveryService\x12\x1a\n" +
	"\bshardkey\x18\v \x01(\tR\bshardkey\x12\x13\n" +
	"\x05sm_id\x18\f \x01(\x05R\x04smId\x12=\n" +
	"\fdate_created\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12\x1b\n" +
	"\toof_shard\x18\x0e \x01(\tR\boofShard\".\n" +
	"\x0fGetOrderRequest\x12\x1b\n" +
	"\torder_uid\x18\x01 \x01(\tR\borderUid\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order2m\n" +
	"\fOrderService\x12]\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/order/{order_uid}B&Z$orderservice/pkg/api/orderpb;orderpbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_proto_goTypes = []any{
	(*Delivery)(nil),              // 0: order.v1.Delivery
	(*Payment)(nil),               // 1: order.v1.Payment
	(*Item)(nil),                  // 2: order.v1.Item
	(*Order)(nil),                 // 3: order.v1.Order
	(*GetOrderRequest)(nil),       // 4: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 5: order.v1.GetOrderResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.v1.Order.delivery:type_name -> order.v1.Delivery
	1, // 1: order.v1.Order.payment:type_name -> order.v1.Payment
	2, // 2: order.v1.Order.items:type_name -> order.v1.Item
	6, // 3: order.v1.Order.date_created:type_name -> google.protobuf.Timestamp
	3, // 4: order.v1.GetOrderResponse.order:type_name -> order.v1.Order
	4, // 5: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	5, // 6: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
